/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UiButton: typeof import('./shared/ui/ui-button/ui/UiButton.vue')['default']
    UiCarousel: typeof import('./shared/ui/ui-carousel/ui/UiCarousel.vue')['default']
    UiCarouselNextSlide: typeof import('./shared/ui/ui-carousel/ui/UiCarouselNextSlide.vue')['default']
    UiCarouselPrevSlide: typeof import('./shared/ui/ui-carousel/ui/UiCarouselPrevSlide.vue')['default']
    UICheckbox: typeof import('./shared/ui/ui-checkbox/ui/UICheckbox.vue')['default']
    UiCheckboxGroup: typeof import('./shared/ui/ui-checkbox-group/ui/UiCheckboxGroup.vue')['default']
    UiDrawer: typeof import('./shared/ui/ui-drawer/ui/UiDrawer.vue')['default']
    UiDropdown: typeof import('./shared/ui/ui-dropdown/ui/UiDropdown.vue')['default']
    UiIcon: typeof import('./shared/ui/ui-icon/ui/UiIcon.vue')['default']
    UiIconButton: typeof import('./shared/ui/ui-icon-button/ui/UiIconButton.vue')['default']
    UiIconSelect: typeof import('./shared/ui/ui-icon-select/ui/UiIconSelect.vue')['default']
    UiImage: typeof import('./shared/ui/ui-image/ui/UiImage.vue')['default']
    UiInput: typeof import('./shared/ui/ui-input/ui/UiInput.vue')['default']
    UiLine: typeof import('./shared/ui/ui-line/ui/UiLine.vue')['default']
    UiLogo: typeof import('./shared/ui/ui-logo/ui/UiLogo.vue')['default']
    UiLogoName: typeof import('./shared/ui/ui-logo-name/ui/UiLogoName.vue')['default']
    UiPagination: typeof import('./shared/ui/ui-pagination/ui/UiPagination.vue')['default']
    UiRadioButton: typeof import('./shared/ui/ui-radio-button/ui/UiRadioButton.vue')['default']
    UiRadioButtonGroup: typeof import('./shared/ui/ui-radio-button-group/ui/UiRadioButtonGroup.vue')['default']
    UiSection: typeof import('./shared/ui/ui-section/ui/UiSection.vue')['default']
    UiTabs: typeof import('./shared/ui/ui-tabs/ui/UiTabs.vue')['default']
    UiTextCollapse: typeof import('./shared/ui/ui-text-collapse/ui/UiTextCollapse.vue')['default']
    UiUploadInput: typeof import('./shared/ui/ui-upload-input/ui/UiUploadInput.vue')['default']
    UiVideo: typeof import('./shared/ui/ui-video/ui/UiVideo.vue')['default']
  }
}
